services:
  - type: web
    name: r10-instagram-publisher
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: IG_ACCESS_TOKEN
        sync: false
      - key: IG_BUSINESS_ID
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama3-8b-8192
      - key: PUBLIC_BASE_URL
        sync: false
